pull_request_rules:
  - name: Automatic merge Guillaume's pull requests without CI
    conditions:
      - author=guillaumeoj
      - label=no-review
      - label=no-ci
    actions:
      merge:
        method: merge
  - name: Automatic merge Guillaume's pull requests with CI
    conditions:
      - author=guillaumeoj
      - label!=work-in-progress
      - label!=manual merge
      - "status-success=Travis CI - Branch"
    actions:
      merge:
        method: merge
