pull_request_rules:
  - name: Automatic merge Guillaume's pull requests without CI
    conditions:
      - "author=GuillaumeOj"
    actions:
      merge:
        strict: "smart"
        method: "rebase"
      delete_head_branch:
        force: True
